#!/bin/sh
# This is a script to get the class string of a window.
# just run the script and click on a window

#xprop WM_CLASS | grep -o '"[^"]*"' | sed 1q
xprop | awk '
	/^WM_CLASS/{sub(/.* =/, "instance:"); sub(/,/, "\nclass:"); print}
	/^WM_NAME/{sub(/.* =/, "title:"); print}'
